# This file was generated by GoReleaser. DO NOT EDIT.
cask "permea" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "daab4722fa574e455ab8ab1af5e778e8b167a7d69b9bce8b545885b48a4dcd9c"
      url "https://github.com/permea-dev/agent/releases/download/v#{version}/permea_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "93ff00e8b6cf6163c3d4a4b5119715d99ee4b28e94d89ff10c32ee1926725ad1"
      url "https://github.com/permea-dev/agent/releases/download/v#{version}/permea_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4d0e50999a635c9cc4f7aecd67a9113b3e622a03bcd1243269d261ef1f4fa289"
      url "https://github.com/permea-dev/agent/releases/download/v#{version}/permea_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "47e0e96758ad892e70f1e5a0a92d4f95eb7c7d7eae3f03749c8155176f73e161"
      url "https://github.com/permea-dev/agent/releases/download/v#{version}/permea_#{version}_linux_amd64.tar.gz"
    end
  end

  name "permea"
  desc "Medidor local de coste de IA con frontera de datos (local-first)"
  homepage "https://github.com/permea-dev/agent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permea"

  # No zap stanza required
end
