# This file was generated by GoReleaser. DO NOT EDIT.
cask "permea" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "a95e834ae6fb2a7d982b3e9e6e39c028dd1e3d36890dd2e670dc647093de01fb"
      url "https://github.com/permea-dev/agent/releases/download/v#{version}/permea_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4c58a522077f7d092cf360ce5004c9f95cd51cb7659b23b2383222346b261628"
      url "https://github.com/permea-dev/agent/releases/download/v#{version}/permea_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f71287c8725b6cbc093b6bd1f05b76d2c8afbaefbcee161319ed660cb5a45aca"
      url "https://github.com/permea-dev/agent/releases/download/v#{version}/permea_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e20977563d58900a8bce99ebcf7cd7e9171263e029ffe11a90a016255d4b855a"
      url "https://github.com/permea-dev/agent/releases/download/v#{version}/permea_#{version}_linux_amd64.tar.gz"
    end
  end

  name "permea"
  desc "Medidor local de coste de IA con frontera de datos (local-first)"
  homepage "https://github.com/permea-dev/agent"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permea"

  # No zap stanza required
end
