# This file was generated by GoReleaser. DO NOT EDIT.
cask "permea" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "e528fce3ae01c6e41ab13abe7078fb0ea0f656e84f569adc933c3769011a3f6e"
      url "https://github.com/bfgnet/agente_permea/releases/download/v#{version}/permea_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2ec9fa6a8d74ee52cb4af30157e5947ce315ef0caab96d7ef1d24f9c8184b930"
      url "https://github.com/bfgnet/agente_permea/releases/download/v#{version}/permea_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8c8b85e7c831adb9f15be58c3440edb6ee9cd27664cabad7182c1847c4a5546a"
      url "https://github.com/bfgnet/agente_permea/releases/download/v#{version}/permea_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "425fa8a875fd4320635592f73a0536482bda23bb7c2c7fc626f92296a0bb22de"
      url "https://github.com/bfgnet/agente_permea/releases/download/v#{version}/permea_#{version}_linux_arm64.tar.gz"
    end
  end

  name "permea"
  desc "Medidor local de coste de IA con frontera de datos (local-first)"
  homepage "https://github.com/bfgnet/agente_permea"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "permea"

  # No zap stanza required

end
